/**
 * add_readings.js
 * scene_map.json の英語技術用語を含むセリフに reading フィールドを追加する
 * Usage: node tools/add_readings.js <project_dir>
 */
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
if (args.length === 0) { console.error('Usage: node add_readings.js <project_dir>'); process.exit(1); }

const PRES_ROOT = path.resolve(__dirname, '..');
const PROJECT_DIR = path.resolve(PRES_ROOT, args[0]);
const MAP_FILE = path.join(PROJECT_DIR, 'scene_map.json');

// バックアップから復元（もしあれば）
const BAK_FILE = MAP_FILE + '.bak';
if (fs.existsSync(BAK_FILE)) {
  fs.copyFileSync(BAK_FILE, MAP_FILE);
  console.log('Restored from backup');
}

const map = JSON.parse(fs.readFileSync(MAP_FILE, 'utf-8'));

// プレースホルダ方式: 長いものから先に置換してプレースホルダに、最後に戻す
const DICT = [
  // 最長一致を優先（部分文字列の衝突を防ぐ）
  // ★ proj_ede76869: インターネットは誰が作って誰が管理しているのか（長いフレーズを先に）
  ['Internet-Draft', 'インターネットドラフト'],
  ['Cloudflare', 'クラウドフレア'],
  ['ARPANET', 'アーパネット'],
  ['Gateway', 'ゲートウェイ'],
  ['Request', 'リクエスト'],
  ['YouTube', 'ユーチューブ'],
  ['Border', 'ボーダー'],
  ['Google', 'グーグル'],
  ['Comments', 'コメンツ'],
  ['Protocol', 'プロトコル'],
  ['Facebook', 'フェイスブック'],
  ['ICANN', 'アイキャン'],
  ['JUNET', 'ジェイユーネット'],
  ['ISDN', 'アイエスディーエヌ'],
  ['ADSL', 'エーディーエスエル'],
  ['IETF', 'アイイーティーエフ'],
  ['WIDE', 'ワイド'],
  ['RPKI', 'アールピーケーアイ'],
  ['IANA', 'アイアナ'],
  ['Tier', 'ティア'],
  ['UCLA', 'ユーシーエルエー'],
  ['RAND', 'ランド'],
  ['HTTP', 'エイチティーティーピー'],
  ['BGP', 'ビージーピー'],
  ['DNS', 'ディーエヌエス'],
  ['ISP', 'アイエスピー'],
  ['RFC', 'アールエフシー'],
  ['AWS', 'エーダブリューエス'],
  ['GCP', 'ジーシーピー'],
  ['TCP', 'ティーシーピー'],
  ['Web', 'ウェブ'],
  ['Meta', 'メタ'],
  ['IP', 'アイピー'],
  ['AS', 'エーエス'],
  ['AI', 'エーアイ'],
  ['Qualcomm', 'クアルコム'],
  ['com', 'コム'],
  ['for', 'フォー'],
  ['jp', 'ジェーピー'],
  ['X', 'エックス'],
  // ★ proj_614d0f20: アルゴリズムって結局なんなのか（長いフレーズを先に）
  ['PageRank', 'ページランク'],
  ['Algoritmi', 'アルゴリトミ'],
  ['algebra', 'アルジェブラ'],
  ['GPS', 'ジーピーエス'],
  ['NP', 'エヌピー'],
  // ★ proj_afbe778d: プログラミングとは何か（長いフレーズを先に）
  ['Computational Thinking', 'コンピューテーショナル シンキング'],
  ['SlashData', 'スラッシュデータ'],
  ['Dijkstra', 'ダイクストラ'],
  ['FORTRAN', 'フォートラン'],
  ['Knuth', 'クヌース'],
  ['IKEA', 'イケア'],
  ['IDC', 'アイディーシー'],
  ['ADD', 'アド'],
  ['MOV', 'ムーブ'],
  // ★ proj_352c4df4: ネットに一度上げた写真はなぜ完全に消せないのか
  ['Perma-Cache', 'パーマキャッシュ'],
  ['Wayback Machine', 'ウェイバック マシン'],
  ['Cloudflare', 'クラウドフレア'],
  ['Snapchat', 'スナップチャット'],
  ['ARPANET', 'アーパネット'],
  ['FAT32', 'ファットサンジュウニ'],
  ['NTFS', 'エヌティーエフエス'],
  ['ext4', 'イーエックスティーフォー'],
  ['TRIM', 'トリム'],
  ['GDPR', 'ジーディーピーアール'],
  ['EXIF', 'イグジフ'],
  ['HTTP', 'エイチティーティーピー'],
  ['DELETE', 'デリート'],
  ['CDN', 'シーディーエヌ'],
  ['DRM', 'ディーアールエム'],
  ['SSD', 'エスエスディー'],
  ['SNS', 'エスエヌエス'],
  ['TCP', 'ティーシーピー'],
  ['Meta', 'メタ'],
  ['Web', 'ウェブ'],
  ['Google', 'グーグル'],
  ['Wayback', 'ウェイバック'],
  ['Machine', 'マシン'],
  ['IP', 'アイピー'],
  ['OS', 'オーエス'],
  ['EU', 'イーユー'],
  // ★ proj_539006a7: パスワードセキュリティ（最長フレーズを最優先で配置）
  ['Password Hashing Competition', 'パスワード ハッシング コンペティション'],
  ['Krebs on Security', 'クレブス オン セキュリティ'],
  ['Have I Been Pwned', 'ハブ アイ ビーン ポウンド'],
  ['FIDO Alliance', 'ファイド アライアンス'],
  ['Hive Systems', 'ハイブ システムズ'],
  ['SHALL NOT', 'シャル ノット'],
  ['Bill Burr', 'ビル バー'],
  ['Password123', 'パスワードいちにさん'],
  ['Argon2id', 'アルゴンツーアイディー'],
  ['mycatlikestuna', 'マイキャットライクスツナ'],
  ['P@ss1234', 'ピーアットエスエスいちにさんよん'],
  ['LastPass', 'ラストパス'],
  ['NordPass', 'ノードパス'],
  ['LinkedIn', 'リンクトイン'],
  ['Verizon', 'ベライゾン'],
  ['Password', 'パスワード'],
  ['Hashing', 'ハッシング'],
  ['Argon2', 'アルゴンツー'],
  ['bcrypt', 'ビークリプト'],
  ['scrypt', 'エスクリプト'],
  ['FIDO2', 'ファイドツー'],
  ['SHALL', 'シャル'],
  ['Yahoo', 'ヤフー'],
  ['DBIR', 'ディービーアイアール'],
  ['SHA-1', 'エスエイチエーワン'],
  ['FIDO', 'ファイド'],
  ['log₂', 'ログツー'],
  ['Burr', 'バー'],
  ['Bill', 'ビル'],
  ['Krebs', 'クレブス'],
  ['Security', 'セキュリティ'],
  ['Alliance', 'アライアンス'],
  ['Competition', 'コンペティション'],
  ['Systems', 'システムズ'],
  ['Hive', 'ハイブ'],
  ['SHA', 'エスエイチエー'],
  ['RTX', 'アールティーエックス'],
  ['MD5', 'エムディーファイブ'],
  ['DES', 'デス'],
  ['MFA', 'エムエフエー'],
  ['SIM', 'シム'],
  ['USPTO', 'ユーエスピーティーオー'],
  ['FBI', 'エフビーアイ'],
  ['CISA', 'シーアイエスエー'],
  ['BEC', 'ビーイーシー'],
  ['AiTM', 'エーアイティーエム'],
  ['Pwned', 'ポウンド'],
  ['GPU1', 'ジーピーユーいち'],
  ['crypt', 'クリプト'],
  // ★ wi_fi: Wi-Fi関連用語（長いフレーズを先に）
  ['Wi-Fi', 'ワイファイ'],
  ['iBwave', 'アイビーウェーブ'],
  ['NIST', 'ニスト'],
  ['MIMO', 'マイモ'],
  ['SSID', 'エスエスアイディー'],
  ['ISM', 'アイエスエム'],
  ['FCC', 'エフシーシー'],
  ['dBm', 'ディービーエム'],
  ['dB', 'ディービー'],
  ['RC', 'アールシー'],
  // ★ 5g_world_change: 最長フレーズを最初に（他プロジェクトの短い語に食われないよう）
  ['Non-Standalone', 'ノンスタンドアローン'],
  ['Standalone', 'スタンドアローン'],
  ['Opensignal', 'オープンシグナル'],
  ['Netflix', 'ネットフリックス'],
  ['TikTok', 'ティックトック'],
  ['Sprint', 'スプリント'],
  ['i-mode', 'アイモード'],
  ['Sub-6', 'サブシックス'],
  ['20Gbps', 'にじゅうギガビーピーエス'],
  ['140Mbps', 'ひゃくよんじゅうメガビーピーエス'],
  ['47Mbps', 'よんじゅうななメガビーピーエス'],
  ['939Mbps', 'きゅうひゃくさんじゅうきゅうメガビーピーエス'],
  ['1Gbps', 'いちギガビーピーエス'],
  ['64kbps', 'ろくじゅうよんキロビーピーエス'],
  ['20Mbps', 'にじゅうメガビーピーエス'],
  ['3-8MB', 'さんからはちメガバイト'],
  ['AT&T', 'エーティーアンドティー'],
  ['IOWN', 'アイオン'],
  ['FOMA', 'フォーマ'],
  ['NSA', 'エヌエスエー'],
  ['SMS', 'エスエムエス'],
  ['SA', 'エスエー'],
  ['Gbps', 'ギガビーピーエス'],
  ['Mbps', 'メガビーピーエス'],
  ['kbps', 'キロビーピーエス'],
  ['GHz', 'ギガヘルツ'],
  ['MHz', 'メガヘルツ'],
  ['LTE', 'エルティーイー'],
  ['ICT', 'アイシーティー'],
  ['NTT', 'エヌティーティー'],
  ['SNS', 'エスエヌエス'],
  ['Zoom', 'ズーム'],
  ['5G E', 'ファイブジーイー'],
  ['5G', 'ファイブジー'],
  ['4G', 'フォージー'],
  ['3G', 'スリージー'],
  ['2G', 'ツージー'],
  ['1G', 'ワンジー'],
  ['8K', 'はちケー'],
  // ★ free_app_real_price: App/Go等の短い語より先に処理すべき長い語
  ['Pew Research Center', 'ピュー リサーチ センター'],
  ['DuckDuckGo', 'ダックダックゴー'],
  ['WhatsApp', 'ワッツアップ'],
  ['Firefox', 'ファイアフォックス'],
  ['Proton', 'プロトン'],
  // ★ 短い汎用単語(to, Me, Face等)より先に処理すべき長い単語
  ['App Tracking Transparency', 'アップ トラッキング トランスペアレンシー'],
  ['Transparency', 'トランスペアレンシー'],
  ['Instagram', 'インスタグラム'],
  ['Wikipedia', 'ウィキペディア'],
  ['Facebook', 'フェイスブック'],
  ['Tracking', 'トラッキング'],
  ['YouTube', 'ユーチューブ'],
  ['Apple', 'アップル'],
  ['Store', 'ストア'],
  ['Meta', 'メタ'],
  ['LINE', 'ライン'],
  ['Play', 'プレイ'],
  ['App', 'アップ'],
  ['ATT', 'エーティーティー'],
  ['RTB', 'アールティービー'],
  ['CM', 'シーエム'],
  // minecraft_seed_randomness specific (長いフレーズ先)
  ['Minecraft@Home', 'マインクラフトアットホーム'],
  ['Minecraft', 'マインクラフト'],
  ['pack.png', 'パックピング'],
  ['Cloudflare', 'クラウドフレア'],
  ['NVIDIA', 'エヌビディア'],
  ['Perlin', 'パーリン'],
  ['Ubuntu', 'ウブントゥ'],
  ['Notch', 'ノッチ'],
  ['Ken', 'ケン'],
  ['Bedrock', 'ベッドロック'],
  ['Alpha', 'アルファ'],
  ['CDN', 'シーディーエヌ'],
  ['Home', 'ホーム'],
  // accurate_random_numbers specific (長いフレーズ先)
  ['xorshift128+', 'エックスオアシフト ひゃくにじゅうはちプラス'],
  ['Math.random', 'マスドットランダム'],
  ['/dev/urandom', 'スラッシュデブ スラッシュユーランダム'],
  ['/dev/random', 'スラッシュデブ スラッシュランダム'],
  ['ChaCha20', 'チャチャトゥエンティ'],
  ['OpenSSL', 'オープンエスエスエル'],
  ['Android', 'アンドロイド'],
  ['FreeBSD', 'フリービーエスディー'],
  ['Bitcoin', 'ビットコイン'],
  ['Samsung', 'サムスン'],
  ['urandom', 'ユーランダム'],
  ['secrets', 'シークレッツ'],
  ['CSPRNG', 'シーエスピーアールエヌジー'],
  ['RDRAND', 'アールディーランド'],
  ['Debian', 'デビアン'],
  ['random', 'ランダム'],
  ['ECDSA', 'イーシーディーエスエー'],
  ['RANDU', 'ランドゥ'],
  ['Linux', 'リナックス'],
  ['Intel', 'インテル'],
  ['PRNG', 'ピーアールエヌジー'],
  ['RAND', 'ランド'],
  ['rand', 'ランド'],
  ['PS3', 'ピーエススリー'],
  ['BTC', 'ビーティーシー'],
  ['IBM', 'アイビーエム'],
  ['LCG', 'エルシージー'],
  ['SSL', 'エスエスエル'],
  ['SSH', 'エスエスエイチ'],
  ['NSA', 'エヌエスエー'],
  ['ID', 'アイディー'],
  // what_was_web3: to/in等に食われる前の最長フレーズ（最優先）
  ['Tim Berners-Lee', 'ティム バーナーズリー'],
  ['Satoshi Nakamoto', 'サトシ ナカモト'],
  ['Berners-Lee', 'バーナーズリー'],
  ['Tim', 'ティム'],
  // lobotomy_nobel_worst_surgery specific (長いフレーズ先)
  ['My Lobotomy', 'マイ ロボトミー'],
  ['Lobotomy', 'ロボトミー'],
  ['JFK', 'ジェイエフケー'],
  ['NPR', 'エヌピーアール'],
  ['DBS', 'ディービーエス'],
  ['My', 'マイ'],
  // facial_expression_emotion_myth specific (長いフレーズ先)
  ['Azure Face API', 'アジュール フェイス エーピーアイ'],
  ['Lie to Me', 'ライ トゥー ミー'],
  ['HireVue', 'ハイアービュー'],
  ['Microsoft', 'マイクロソフト'],
  ['Pixar', 'ピクサー'],
  ['Azure', 'アジュール'],
  ['SPOT', 'スポット'],
  ['FACS', 'ファックス'],
  ['TIME', 'タイム'],
  ['Face', 'フェイス'],
  ['TSA', 'ティーエスエー'],
  ['GAO', 'ジーエーオー'],
  ['Lie', 'ライ'],
  ['Me', 'ミー'],
  ['Alex Krizhevsky', 'アレックス クリジェフスキー'],
  ['Krizhevsky', 'クリジェフスキー'],
  ['Trainium2', 'トレイニアムツー'],
  ['Triton', 'トライトン'],
  ['to', 'トゥー'],
  ['EU', 'イーユー'],
  ['CG', 'シージー'],
  // meditation_scientific_effects specific (長いフレーズ先)
  ['Search Inside Yourself', 'サーチ インサイド ユアセルフ'],
  ['Journal of Neuroscience', 'ジャーナル オブ ニューロサイエンス'],
  ['Mind the Hype', 'マインド ザ ハイプ'],
  ['McMindfulness', 'マックマインドフルネス'],
  ['Neuroscience', 'ニューロサイエンス'],
  ['Headspace', 'ヘッドスペース'],
  ['Fortune', 'フォーチュン'],
  ['Journal', 'ジャーナル'],
  ['Inside', 'インサイド'],
  ['Search', 'サーチ'],
  ['NCCIH', 'エヌシーシーアイエイチ'],
  ['MBSR', 'エムビーエスアール'],
  ['JAMA', 'ジャマ'],
  ['Calm', 'カーム'],
  ['Mind', 'マインド'],
  ['Hype', 'ハイプ'],
  ['DMN', 'ディーエムエヌ'],
  ['CBT', 'シービーティー'],
  ['vs', 'バーサス'],
  // happiness_genetics specific (長いフレーズ先)
  ['The How of Happiness', 'ザ ハウ オブ ハピネス'],
  ['Happiness', 'ハピネス'],
  ['DNA', 'ディーエヌエー'],
  ['GDP', 'ジーディーピー'],
  // math_for_programmers specific (長いフレーズ先)
  ['Nature Scientific Reports', 'ネイチャー サイエンティフィック リポーツ'],
  ['Web Dev Simplified', 'ウェブ デブ シンプリファイド'],
  ['Unreal Engine', 'アンリアル エンジン'],
  ['Northeastern', 'ノースイースタン'],
  ['ChatGPT', 'チャットジーピーティー'],
  ['Simplified', 'シンプリファイド'],
  ['Coursera', 'コーセラ'],
  ['boolean', 'ブーリアン'],
  ['Reports', 'リポーツ'],
  ['Unreal', 'アンリアル'],
  ['Engine', 'エンジン'],
  ['Unity', 'ユニティ'],
  ['Block', 'ブロック'],
  ['false', 'フォルス'],
  ['true', 'トゥルー'],
  ['Big O', 'ビッグ オー'],
  ['CRUD', 'クラッド'],
  ['ACM', 'エーシーエム'],
  ['RSA', 'アールエスエー'],
  ['ORM', 'オーアールエム'],
  ['edX', 'イーディーエックス'],
  ['Dev', 'デブ'],
  ['AND', 'アンド'],
  ['NOT', 'ノット'],
  ['sin', 'サイン'],
  ['cos', 'コサイン'],
  ['tan', 'タンジェント'],
  ['OFF', 'オフ'],
  ['Big', 'ビッグ'],
  ['ML', 'エムエル'],
  ['OK', 'オーケー'],
  ['ON', 'オン'],
  ['OR', 'オア'],
  // free_will_existence specific (長いフレーズ先)
  ['Scientific American', 'サイエンティフィック アメリカン'],
  ['Free Agents', 'フリー エージェンツ'],
  ['Free Will', 'フリー ウィル'],
  ['PhilPapers', 'フィルペーパーズ'],
  ['Determined', 'ディターミンド'],
  ['Scientific', 'サイエンティフィック'],
  ['American', 'アメリカン'],
  ['Agents', 'エージェンツ'],
  ['elife', 'イーライフ'],
  ['Free', 'フリー'],
  ['Will', 'ウィル'],
  ['PNAS', 'ピーナス'],
  ['Maoz', 'マオズ'],
  ['EEG', 'イーイージー'],
  ['NPO', 'エヌピーオー'],
  ['Uri', 'ウリ'],
  // what_was_web3: 短い語(in, to)に食われる前に処理すべき長い語
  ['Satoshi Nakamoto', 'サトシ ナカモト'],
  ['Moxie Marlinspike', 'モクシー マーリンスパイク'],
  ['Vitalik Buterin', 'ヴィタリック ブテリン'],
  ['Tim Berners-Lee', 'ティム バーナーズリー'],
  ['Greater Fool Theory', 'グレーター フール セオリー'],
  ['Jack Dorsey', 'ジャック ドーシー'],
  ['Gavin Wood', 'ギャビン ウッド'],
  ['CB Insights', 'シービー インサイツ'],
  ['DappRadar', 'ダップレーダー'],
  ['JPMorgan', 'ジェイピーモルガン'],
  ['OpenSea', 'オープンシー'],
  ['Celsius', 'セルシウス'],
  ['Voyager', 'ボイジャー'],
  ['Solana', 'ソラナ'],
  ['Kindle', 'キンドル'],
  ['Dorsey', 'ドーシー'],
  ['Satoshi', 'サトシ'],
  ['Nakamoto', 'ナカモト'],
  ['Buterin', 'ブテリン'],
  ['Vitalik', 'ヴィタリック'],
  ['Greater', 'グレーター'],
  ['Theory', 'セオリー'],
  ['Fool', 'フール'],
  ['Moxie', 'モクシー'],
  ['Marlinspike', 'マーリンスパイク'],
  ['Luna', 'ルナ'],
  ['GAFA', 'ガーファ'],
  ['BAN', 'バン'],
  // sleepwalking_brain_science specific (長いフレーズ先)
  ['Archives of Disease in Childhood', 'アーカイブズ オブ ディジーズ イン チャイルドフッド'],
  ['Rapid Eye Movement', 'ラピッド アイ ムーブメント'],
  ['HLA DQB1', 'エイチエルエー ディーキュービーワン'],
  ['lunaticus', 'ルナティクス'],
  ['lunatic', 'ルナティック'],
  ['Archives', 'アーカイブズ'],
  ['Childhood', 'チャイルドフッド'],
  ['Movement', 'ムーブメント'],
  ['Disease', 'ディジーズ'],
  ['Ohayon', 'オハヨン'],
  ['Rapid', 'ラピッド'],
  ['SEEG', 'エスイーイージー'],
  ['DQB1', 'ディーキュービーワン'],
  ['RBD', 'アールビーディー'],
  ['HLA', 'エイチエルエー'],
  ['Eye', 'アイ'],
  ['N2', 'エヌツー'],
  ['km', 'キロ'],
  ['Lightning', 'ライトニング'],
  ['in', 'イン'],
  // sleepwalking_neuroscience specific
  ['Nature Reviews Neurology', 'ネイチャー レビューズ ニューロロジー'],
  ['Nature Communications', 'ネイチャー コミュニケーションズ'],
  ['The Lancet', 'ザ ランセット'],
  ['PLOS ONE', 'プロスワン'],
  ['Communications', 'コミュニケーションズ'],
  ['Neurology', 'ニューロロジー'],
  ['Reviews', 'レビューズ'],
  ['Lancet', 'ランセット'],
  ['Nature', 'ネイチャー'],
  ['SPECT', 'スペクト'],
  ['SLEEP', 'スリープ'],
  ['NREM', 'ノンレム'],
  ['PLOS', 'プロス'],
  ['GABA', 'ガバ'],
  ['FDA', 'エフディーエー'],
  ['EEG', 'イーイージー'],
  ['PMC', 'ピーエムシー'],
  ['REM', 'レム'],
  ['ONE', 'ワン'],
  ['The', 'ザ'],
  ['N1', 'エヌワン'],
  ['N3', 'エヌスリー'],
  // lie_detector_myth / free_will_existence specific
  ['eLife', 'イーライフ'],
  ['fMRI', 'エフエムアールアイ'],
  ['P300', 'ピーサンビャク'],
  ['CIA', 'シーアイエー'],
  ['CQT', 'シーキューティー'],
  ['DNA', 'ディーエヌエー'],
  ['FBI', 'エフビーアイ'],
  ['KGB', 'カーゲーベー'],
  ['MRI', 'エムアールアイ'],
  ['NSA', 'エヌエスエー'],
  // cuda_grip_on_ai specific
  ['Stack Overflow', 'スタックオーバーフロー'],
  ['Jensen Huang', 'ジェンスン ファン'],
  ['Jensen', 'ジェンスン'],
  ['Huang', 'ファン'],
  ['AlexNet', 'アレックスネット'],
  ['Alex', 'アレックス'],
  ['Ian Buck', 'イアン バック'],
  ['Buck', 'バック'],
  ['Ian', 'イアン'],
  ['BrookGPU', 'ブルックジーピーユー'],
  ['Brook', 'ブルック'],
  ['GeForce 8800 GTX', 'ジーフォース はっせんはっぴゃく ジーティーエックス'],
  ['GeForce', 'ジーフォース'],
  ['GTX 580', 'ジーティーエックス ごひゃくはちじゅう'],
  ['TensorRT', 'テンサーアールティー'],
  ['TensorFlow', 'テンサーフロー'],
  ['DeepSpeed', 'ディープスピード'],
  ['Apple Silicon', 'アップルシリコン'],
  ['Anthropic', 'アンスロピック'],
  ['PyTorch', 'パイトーチ'],
  ['Modular', 'モジュラー'],
  ['MI300X', 'エムアイ さんぜんエックス'],
  ['MI300', 'エムアイ さんぜん'],
  ['MIOpen', 'エムアイオープン'],
  ['OpenAI', 'オープンエーアイ'],
  ['Trainium2', 'トレイニアムツー'],
  ['Triton', 'トライトン'],
  ['Silicon', 'シリコン'],
  ['cuDNN', 'シーユーディーエヌエヌ'],
  ['H100', 'エイチひゃく'],
  ['CUDA', 'クーダ'],
  ['NCCL', 'エヌシーシーエル'],
  ['ROCm', 'ロックエム'],
  ['Mojo', 'モジョ'],
  ['vLLM', 'ブイエルエルエム'],
  ['GPU', 'ジーピーユー'],
  ['CPU', 'シーピーユー'],
  ['TPU', 'ティーピーユー'],
  ['MLX', 'エムエルエックス'],
  ['v6e', 'ブイシックスイー'],
  ['AMD', 'エーエムディー'],
  ['AWS', 'エーダブリューエス'],
  ['R&D', 'アールアンドディー'],
  ['AI', 'エーアイ'],
  // fullstack_myth specific (長い複合語を先に)
  ['but oftentimes better than a master of one', 'バット オフンタイムズ ベター ザン ア マスター オブ ワン'],
  ['Jack of all trades, master of none', 'ジャック オブ オール トレーズ、マスター オブ ノン'],
  ['One Person Framework', 'ワンパーソンフレームワーク'],
  ['Dan Abramov', 'ダン アブラモフ'],
  ['Ruby on Rails', 'ルビー オン レイルズ'],
  ['Rails World', 'レイルズ ワールド'],
  ['Kubernetes', 'クバネティス'],
  ['MongoDB', 'モンゴデービー'],
  ['LinkedIn', 'リンクトイン'],
  ['Flexbox', 'フレックスボックス'],
  ['Spotify', 'スポティファイ'],
  ['oftentimes', 'オフンタイムズ'],
  ['Framework', 'フレームワーク'],
  ['Abramov', 'アブラモフ'],
  ['Docker', 'ドッカー'],
  ['Cursor', 'カーソル'],
  ['better', 'ベター'],
  ['master', 'マスター'],
  ['trades', 'トレーズ'],
  ['Person', 'パーソン'],
  ['Redis', 'レディス'],
  ['MySQL', 'マイエスキューエル'],
  ['gRPC', 'ジーアールピーシー'],
  ['Grid', 'グリッド'],
  ['Next.js', 'ネクストジェイエス'],
  ['GraphQL', 'グラフキューエル'],
  ['Jack', 'ジャック'],
  ['none', 'ノン'],
  ['than', 'ザン'],
  ['REST', 'レスト'],
  ['PHP', 'ピーエイチピー'],
  ['One', 'ワン'],
  ['all', 'オール'],
  ['but', 'バット'],
  // readable_code specific
  ['AbstractSingletonProxyFactoryBean', 'アブストラクト シングルトン プロキシ ファクトリー ビーン'],
  ['id Software', 'アイディー ソフトウェア'],
  ['Clean Code', 'クリーンコード'],
  ['Readability', 'リーダビリティ'],
  ['PostgreSQL', 'ポストグレスキューエル'],
  ['SQLite', 'エスキューライト'],
  ['Software', 'ソフトウェア'],
  ['switch', 'スイッチ'],
  ['Clean', 'クリーン'],
  ['Code', 'コード'],
  ['code', 'コード'],
  ['if', 'イフ'],
  ['id', 'アイディー'],
  ['Crafting Interpreters', 'クラフティング インタープリターズ'],
  ['Stack Overflow Developer Survey', 'スタックオーバーフロー デベロッパーサーベイ'],
  ['Windows Subsystem for Linux', 'ウィンドウズ サブシステム フォー リナックス'],
  ['Classic Mac OS', 'クラシック マック オーエス'],
  ['Apple Silicon', 'アップルシリコン'],
  ['Active Directory', 'アクティブディレクトリ'],
  ['Microsoft365', 'マイクロソフトさんろくご'],
  ['Docker Desktop', 'ドッカーデスクトップ'],
  ['Visual Studio', 'ビジュアルスタジオ'],
  ['Silicon Valley', 'シリコンバレー'],
  ['Mac OS X', 'マック オーエス テン'],
  ['MacBook Pro', 'マックブックプロ'],
  ['MacBook Air', 'マックブックエアー'],
  ['brew install postgresql', 'ブリュー インストール ポストグレスキューエル'],
  ['brew install python', 'ブリュー インストール パイソン'],
  ['brew install node', 'ブリュー インストール ノード'],
  ['brew update', 'ブリュー アップデート'],
  ['iOS/macOS', 'アイオーエス、マックオーエス'],
  ['App Store', 'アップストア'],
  ['Rosetta 2', 'ロゼッタ ツー'],
  ['VS Code', 'ブイエスコード'],
  ['Node.js', 'ノードジェイエス'],
  ['NeXTSTEP', 'ネクストステップ'],
  ['Objective-C', 'オブジェクティブ シー'],
  ['Homebrew', 'ホームブルー'],
  ['DirectX', 'ダイレクトエックス'],
  ['MacBook', 'マックブック'],
  ['iPhone', 'アイフォーン'],
  ['iPadOS', 'アイパッドオーエス'],
  ['macOS', 'マックオーエス'],
  ['Copland', 'コープランド'],
  ['Taligent', 'タリジェント'],
  ['Python', 'パイソン'],
  ['WSL2', 'ダブリューエスエルツー'],
  ['POSIX', 'ポジックス'],
  ['Xcode', 'エックスコード'],
  ['NeXT', 'ネクスト'],
  ['Mach', 'マーク'],        // Macより先！
  ['IEEE', 'アイトリプルイー'],
  ['CERN', 'セルン'],
  ['Microsoft', 'マイクロソフト'],
  ['Unix', 'ユニックス'],
  ['.NET', 'ドットネット'],
  ['Qiita', 'キータ'],
  ['Zenn', 'ゼン'],
  ['Linux', 'リナックス'],
  ['Windows', 'ウィンドウズ'],
  ['Mac', 'マック'],          // Machの後で
  ['iOS', 'アイオーエス'],
  ['Core Web Vitals', 'コア ウェブ バイタルズ'],  // Webより先！
  ['WebAssembly', 'ウェブアセンブリ'],  // Webより先！
  ['web3', 'ウェブスリー'],  // Webより先！
  ['Web3', 'ウェブスリー'],  // Webより先！
  ['Web2', 'ウェブツー'],    // Webより先！
  ['Web1', 'ウェブワン'],    // Webより先！
  ['Web', 'ウェブ'],
  ['CPU', 'シーピーユー'],
  ['GUI', 'ジーユーアイ'],
  ['CEO', 'シーイーオー'],
  ['EXE', 'エグゼ'],
  ['IoT', 'アイオーティー'],
  ['ARM', 'アーム'],
  ['BSD', 'ビーエスディー'],
  ['x86', 'エックスはちろく'],
  ['C#', 'シーシャープ'],
  ['UI', 'ユーアイ'],
  ['MIT', 'エムアイティー'],
  ['IT', 'アイティー'],
  ['M系', 'エムけい'],
  ['AWS', 'エーダブリューエス'],
  ['GCP', 'ジーシーピー'],
  ['OS', 'オーエス'],
  // python_dominance
  ['Global Interpreter Lock', 'グローバル インタープリター ロック'],
  ['Stack Overflow', 'スタックオーバーフロー'],
  ['scikit-learn', 'サイキットラーン'],
  ['TensorFlow', 'テンソルフロー'],
  ['Interpreter', 'インタープリター'],
  ['Fortran', 'フォートラン'],
  ['FORTRAN', 'フォートラン'],
  ['NumPy', 'ナムパイ'],
  ['numpy', 'ナムパイ'],
  ['PyTorch', 'パイトーチ'],
  ['pandas', 'パンダス'],
  ['COBOL', 'コボル'],
  ['TIOBE', 'ティオベ'],
  ['PyPI', 'パイピーアイ'],
  ['Rust', 'ラスト'],
  ['Mojo', 'モジョ'],
  ['Julia', 'ジュリア'],
  ['JavaScript', 'ジャバスクリプト'],  // Javaより先！（既存）
  ['Java', 'ジャバ'],
  ['C++', 'シープラスプラス'],
  ['HPC', 'エイチピーシー'],
  ['ATM', 'エーティーエム'],
  ['PEP', 'ペップ'],
  ['GIL', 'ジル'],
  ['Google Maps', 'グーグル マップス'],  // Googleより先！
  ['Google', 'グーグル'],  // Goより先！
  ['Notion', 'ノーション'],  // Noより先！
  ['UC', 'ユーシー'],
  ['CSS', 'シーエスエス'],  // CSより先！
  ['CS', 'シーエス'],
  ['Go', 'ゴー'],
  ['AI', 'エーアイ'],
  ['No', 'ナンバー'],
  ['import', 'インポート'],
  ['for', 'フォー'],
  ['PC', 'ピーシー'],
  ['SNS', 'エスエヌエス'],
  // css_programming_language specific
  ['Stack Overflow Developer Survey', 'スタックオーバーフロー デベロッパーサーベイ'],
  ['Custom Properties', 'カスタム プロパティーズ'],
  ['Container Queries', 'コンテナ クエリーズ'],
  ['CSS Working Group', 'シーエスエス ワーキンググループ'],
  ['Fox-Epstein', 'フォックスエプスタイン'],
  ['State of CSS', 'ステート オブ シーエスエス'],
  ['nth-child', 'エヌスチャイルド'],
  ['Hakon Wium Lie', 'ホーコン ウィウム リー'],
  ['W3Techs', 'ダブリュースリーテックス'],
  ['Nesting', 'ネスティング'],
  ['W3C', 'ダブリュースリーシー'],
  ['Container', 'コンテナ'],
  ['Properties', 'プロパティーズ'],
  ['Queries', 'クエリーズ'],
  ['Working', 'ワーキング'],
  ['Group', 'グループ'],
  ['counter', 'カウンター'],
  ['checked', 'チェックド'],
  ['property', 'プロパティ'],
  ['Rule', 'ルール'],
  ['clamp', 'クランプ'],
  ['hover', 'ホバー'],
  ['State', 'ステート'],
  ['calc', 'カルク'],
  ['Sass', 'サス'],
  ['has', 'ハズ'],
  ['var', 'バー'],
  ['max', 'マックス'],
  ['min', 'ミン'],
  ['Eli', 'イーライ'],
  ['YES', 'イエス'],
  ['NO', 'ノー'],
  ['SQL', 'エスキューエル'],
  ['DSL', 'ディーエスエル'],
  ['of', 'オブ'],
  // creating_programming_language specific
  ['Kotlin Native', 'コトリン ネイティブ'],
  ['ANTLR', 'アントラー'],
  ['HOPL', 'エイチオーピーエル'],
  ['LLVM', 'エルエルブイエム'],
  ['Intel', 'インテル'],
  ['AST', 'エーエスティー'],
  ['JIT', 'ジット'],
  ['BNF', 'ビーエヌエフ'],
  ['ABC', 'エービーシー'],
  ['V8', 'ブイエイト'],
  ['IR', 'アイアール'],
  ['Lexer', 'レキサー'],
  ['Parser', 'パーサー'],
  ['Guido', 'グイド'],
  ['Graydon Hoare', 'グレイドン ホアレ'],
  ['Rob Pike', 'ロブ パイク'],
  ['Ken Thompson', 'ケン トンプソン'],
  ['Swift', 'スウィフト'],
  ['Kotlin', 'コトリン'],
  ['Ruby', 'ルビー'],
  ['TypeScript', 'タイプスクリプト'],
  ['malloc', 'マロック'],
  ['free', 'フリー'],
  // rust_vs_cpp specific
  ['UnrealEngine', 'アンリアルエンジン'],
  ['Unreal Engine', 'アンリアルエンジン'],
  ['Cloudflare', 'クラウドフレア'],
  ['Firecracker', 'ファイアクラッカー'],
  ['Pingora', 'ピンゴーラ'],
  ['Discord', 'ディスコード'],
  ['DARPA', 'ダルパ'],
  ['Android', 'アンドロイド'],
  ['CVE', 'シーブイイー'],
  ['Nginx', 'エンジンエックス'],
  ['nginx', 'エンジンエックス'],
  ['FFI', 'エフエフアイ'],
  ['ONCD', 'オーエヌシーディー'],
  ['Dropbox', 'ドロップボックス'],
  ['WebAssembly', 'ウェブアセンブリ'],
  ['Stack Overflow', 'スタックオーバーフロー'],
  ['SIMD', 'シムド'],
  ['VM', 'ブイエム'],
  // heavy_web_apps specific
  ['Single Page Application', 'シングル ページ アプリケーション'],
  ['Server Components', 'サーバー コンポーネンツ'],
  ['create-react-app', 'クリエイト リアクト アップ'],
  ['HTTP Archive', 'エイチティーティーピー アーカイブ'],
  ['node_modules', 'ノード モジュールズ'],
  ['Space Jam', 'スペース ジャム'],
  ['Hello World', 'ハロー ワールド'],
  ['left-pad', 'レフトパッド'],
  ['ReactDOM', 'リアクトドム'],
  ['A/Bテスト', 'エービーテスト'],
  ['Quake1', 'クエイクワン'],
  ['Facebook', 'フェイスブック'],
  ['Tonsky', 'トンスキー'],
  ['Chrome', 'クローム'],
  ['Figma', 'フィグマ'],
  ['Gmail', 'ジーメール'],
  ['Astro', 'アストロ'],
  ['Slack', 'スラック'],
  ['React', 'リアクト'],
  ['Babel', 'バベル'],
  ['Angular', 'アンギュラー'],
  ['Svelte', 'スベルト'],
  ['Amazon', 'アマゾン'],
  ['Server', 'サーバー'],
  ['Single', 'シングル'],
  ['gzip', 'ジージップ'],
  ['HTMX', 'エイチティーエムエックス'],
  ['HTTP', 'エイチティーティーピー'],
  ['HTML', 'エイチティーエムエル'],
  ['JSON', 'ジェイソン'],
  ['Ajax', 'エイジャックス'],
  ['DOM', 'ドム'],
  ['SPA', 'エスピーエー'],
  ['npm', 'エヌピーエム'],
  ['Vue', 'ビュー'],
  ['JSDoc', 'ジェイエスドック'],  // JSより先！
  ['JS', 'ジェイエス'],
  ['TS', 'ティーエス'],
  ['KB', 'キロバイト'],
  ['MB', 'メガバイト'],
  ['GB', 'ギガバイト'],
  ['3D', 'スリーディー'],
  // typescript_savior_or_killer specific
  ['undefined is not a function', 'アンデファインド イズ ノット ア ファンクション'],
  ['DefinitelyTyped', 'デフィニトリータイプド'],
  ['Anders Hejlsberg', 'アンダース ヘルスバーグ'],
  ['Brendan Eich', 'ブレンダン アイク'],
  ['Conditional Types', 'コンディショナル タイプス'],
  ['Mapped Types', 'マップド タイプス'],
  ['Template Literal Types', 'テンプレート リテラル タイプス'],
  ['Yak Shaving', 'ヤクシェービング'],
  ['Rich Harris', 'リッチ ハリス'],
  ['tsconfig.json', 'ティーエスコンフィグ ジェイソン'],
  ['Flow', 'フロー'],
  ['ts-ignore', 'ティーエス イグノア'],
  ['Copilot', 'コパイロット'],
  ['GitHub', 'ギットハブ'],
  ['VSCode', 'ブイエスコード'],
  ['Airbnb', 'エアビーアンドビー'],
  ['Pascal', 'パスカル'],
  ['Delphi', 'デルファイ'],
  ['Turbo', 'ターボ'],
  ['Rails', 'レイルズ'],
  ['Dart', 'ダート'],
  ['Deno', 'ディーノ'],
  ['Bun', 'バン'],
  ['DHH', 'ディーエイチエイチ'],
  ['TC39', 'ティーシーさんじゅうきゅう'],
  ['undefined', 'アンデファインド'],
  ['function', 'ファンクション'],
  ['any', 'エニー'],
  ['not', 'ノット'],
  // what_was_web3 specific (長いフレーズ先)
  ['Greater Fool Theory', 'グレーター フール セオリー'],
  ['Moxie Marlinspike', 'モクシー マーリンスパイク'],
  ['Three Arrows Capital', 'スリー アローズ キャピタル'],
  ['Celsius Network', 'セルシウス ネットワーク'],
  ['Vitalik Buterin', 'ヴィタリック ブテリン'],
  ['Tim Berners-Lee', 'ティム バーナーズリー'],
  ['Jack Dorsey', 'ジャック ドーシー'],
  ['CB Insights', 'シービー インサイツ'],
  ['Gavin Wood', 'ギャビン ウッド'],
  ['DappRadar', 'ダップレーダー'],
  ['JPMorgan', 'ジェイピーモルガン'],
  ['OpenSea', 'オープンシー'],
  ['Celsius', 'セルシウス'],
  ['Voyager', 'ボイジャー'],
  ['Solana', 'ソラナ'],
  ['Kindle', 'キンドル'],
  ['Greater', 'グレーター'],
  ['Theory', 'セオリー'],
  ['Fool', 'フール'],
  ['GAFA', 'ガーファ'],
  ['BAN', 'バン'],
  ['LP', 'エルピー'],
  ['Reality Labs', 'リアリティー ラブズ'],
  ['Tornado Cash', 'トルネード キャッシュ'],
  ['Mastercard', 'マスターカード'],
  ['Decentraland', 'ディセントラランド'],
  ['dappGambl', 'ダップギャンブル'],
  ['Bloomberg', 'ブルームバーグ'],
  ['Statista', 'スタティスタ'],
  ['Ethereum', 'イーサリアム'],
  ['Christie', 'クリスティーズ'],
  ['TerraUSD', 'テラユーエスディー'],
  ['Alchemy', 'アルケミー'],
  ['YouTube', 'ユーチューブ'],
  ['Twitter', 'ツイッター'],
  ['Beeple', 'ビープル'],
  ['Infura', 'インフュラ'],
  ['Signal', 'シグナル'],
  ['Terra', 'テラ'],
  ['LUNA', 'ルナ'],
  ['USDT', 'ユーエスディーティー'],
  ['USDC', 'ユーエスディーシー'],
  ['Meta', 'メタ'],
  ['Visa', 'ビザ'],
  ['DeFi', 'ディーファイ'],
  ['a16z', 'エーシックスティーンゼット'],
  ['NFT', 'エヌエフティー'],
  ['DAO', 'ダオ'],
  ['ETH', 'イーサ'],
  ['FTX', 'エフティーエックス'],
  ['SBF', 'エスビーエフ'],
  ['TVL', 'ティーブイエル'],
  ['PoS', 'プルーフオブステーク'],
  ['UX', 'ユーエックス'],
  ['VC', 'ブイシー'],
  ['URL', 'ユーアールエル'],
  ['API', 'エーピーアイ'],
  ['CI', 'シーアイ'],
  ['CD', 'シーディー'],
  // free_app_real_price specific (短い語の残骸防止)
  ['Research', 'リサーチ'],
  ['Center', 'センター'],
  ['Cookie', 'クッキー'],
  ['Prime', 'プライム'],
  ['arXiv', 'アーカイブ'],
  ['ARPU', 'エーアールピーユー'],
  ['Pew', 'ピュー'],
  ['Z', 'ゼット'],
  // 5g_world_change: 短い語（SA, au）
  ['SA', 'エスエー'],
  ['au', 'エーユー'],
  // fax specific (長いフレーズ先)
  ['HIPAA', 'ヒパー'],
  ['Teams', 'チームズ'],
  ['CIAJ', 'シーアイエージェイ'],
  ['FAX', 'ファックス'],
  ['CNN', 'シーエヌエヌ'],
  ['DX', 'ディーエックス'],
  ['G3', 'ジースリー'],
  ['A4', 'エーヨン'],
  // ★ proj_7973c0b4: 充電ケーブル（長いフレーズを先に）
  ['Consumer Reports', 'コンシューマー リポーツ'],
  ['Amazon Basics', 'アマゾン ベーシックス'],
  ['Quick Charge', 'クイック チャージ'],
  ['USB-C', 'ユーエスビーシー'],
  ['USB PD', 'ユーエスビー ピーディー'],
  ['e-waste', 'イーウェイスト'],
  ['eMarker', 'イーマーカー'],
  ['MagSafe', 'マグセーフ'],
  ['Consumer', 'コンシューマー'],
  ['Samsung', 'サムスン'],
  ['Reports', 'リポーツ'],
  ['iFixit', 'アイフィクシット'],
  ['Basics', 'ベーシックス'],
  ['Charge', 'チャージ'],
  ['Anker', 'アンカー'],
  ['Quick', 'クイック'],
  ['OPPO', 'オッポ'],
  ['VOOC', 'ブーク'],
  ['NITE', 'ナイト'],
  ['USB', 'ユーエスビー'],
  ['PVC', 'ピーブイシー'],
  ['Qi2', 'チーツー'],
  ['MM', 'エムエム'],
  ['PD', 'ピーディー'],
  ['EU', 'イーユー'],
  // ★ proj_dc16b914: 「クラウド」ってなんなの？（長いフレーズを先に）
  ['Atlassian', 'アトラシアン'],
  ['iCloud', 'アイクラウド'],
  ['signals', 'シグナルズ'],
  ['PayPay', 'ペイペイ'],
  ['Cloud', 'クラウド'],
  ['CLOUD', 'クラウド'],
  ['Azure', 'アジュール'],
  ['IaaS', 'イアース'],
  ['PaaS', 'パース'],
  ['SaaS', 'サース'],
  ['GDPR', 'ジーディーピーアール'],
  ['CIO', 'シーアイオー'],
  ['EC2', 'イーシーツー'],
  ['S3', 'エススリー'],
  ['NG', 'エヌジー'],
  // ★ proj_0_1: 0と1だけでなぜ動画や音楽が再生できるのか（長いフレーズを先に）
  ['H.264', 'エイチニーロクヨン'],
  ['H.265', 'エイチニーロクゴ'],
  ['YouTube', 'ユーチューブ'],
  ['Suica', 'スイカ'],
  ['JPEG', 'ジェイペグ'],
  ['MPEG', 'エムペグ'],
  ['FLAC', 'フラック'],
  ['MP3', 'エムピースリー'],
  ['AAC', 'エーエーシー'],
  ['HD', 'エイチディー'],
  ['DA', 'ディーエー'],
  ['QR', 'キューアール'],
  // ★ proj_qr: QRコード関連（長いフレーズを先に）
  ['WeChat Pay', 'ウィーチャット ペイ'],
  ['Alipay', 'アリペイ'],
  ['M15', 'エム ジュウゴ'],
  ['Q25', 'キュー ニジュウゴ'],
  ['H30', 'エイチ サンジュウ'],
  ['L7', 'エル ナナ'],
  ['WeChat', 'ウィーチャット'],
  ['Response', 'レスポンス'],
  ['NASA', 'ナサ'],
  ['DVD', 'ディーブイディー'],
  ['Pay', 'ペイ'],
  // 検出用（短いDICTエントリによる部分消費の残骸対策）
  ['Lightng', 'ライトニング'],
  ['NE', ''],
  ['NA', ''],
];

// コマンド系は文脈依存なので正規表現で処理
const CMD_REGEX = [
  [/\bls\b/g, 'エルエス'],
  [/\bgrep\b/g, 'グレップ'],
  [/\bsed\b/g, 'セド'],
  [/\bawk\b/g, 'オーク'],
  [/\bcurl\b/g, 'カール'],
  [/\bcp\b/g, 'シーピー'],
  [/\bdir\b/g, 'ディレ'],
  [/\bcopy\b/g, 'コピー'],
  [/\bssh\b/g, 'エスエスエイチ'],
  [/\bfindstr\b/g, 'ファインドストリング'],
  [/\bC言語/g, 'シー言語'],
  [/\bCが/g, 'シーが'],
  [/\bCで/g, 'シーで'],
  [/\bCの/g, 'シーの'],
  [/\bCと/g, 'シーと'],
  [/\bCから/g, 'シーから'],
  [/\bCや/g, 'シーや'],
  [/\bC並み/g, 'シーなみ'],
  [/\bCって/g, 'シーって'],
  [/\bC？/g, 'シー？'],
  [/\bC、/g, 'シー、'],
  [/\bMIT/g, 'エムアイティー'],
  [/(\d+)W\b/g, '$1ワット'],
];

function applyReading(text) {
  let r = text;

  // まずプレースホルダ置換（長い順に）
  const placeholders = [];
  for (let i = 0; i < DICT.length; i++) {
    const [search, replace] = DICT[i];
    const ph = `\x00${i}\x00`;
    if (r.includes(search)) {
      r = r.split(search).join(ph);
      placeholders.push([ph, replace]);
    }
  }
  // プレースホルダをカタカナに戻す
  for (const [ph, replace] of placeholders) {
    r = r.split(ph).join(replace);
  }

  // コマンド系（正規表現）
  for (const [re, replace] of CMD_REGEX) {
    r = r.replace(re, replace);
  }

  // 数値パーセント
  r = r.replace(/(\d+)%→(\d+)%/g, '$1パーセントから$2パーセント');
  r = r.replace(/(\d+)%/g, '$1パーセント');

  // → を「、」に
  r = r.replace(/→/g, '、');

  return r;
}

let modified = 0;
for (const scene of map.scenes) {
  for (const line of scene.lines) {
    // 既存のreadingを削除
    delete line.reading;

    const text = line.text;
    if (/[a-zA-Z]/.test(text) || /[%→]/.test(text)) {
      const reading = applyReading(text);
      if (reading !== text) {
        line.reading = reading;
        modified++;
      }
    }
  }
}

// ===== 未登録英単語の自動検出 =====
// DICT置換後に残った英単語（2文字以上）を検出する
function detectUnregisteredTokens(text) {
  // DICT置換をシミュレート（プレースホルダを空文字に）
  let r = text;
  for (let i = 0; i < DICT.length; i++) {
    const [search] = DICT[i];
    if (r.includes(search)) {
      r = r.split(search).join('');
    }
  }
  // CMD_REGEX置換もシミュレート
  for (const [re] of CMD_REGEX) {
    r = r.replace(re, '');
  }
  // 残った英単語トークンを抽出（2文字以上）
  const remaining = r.match(/[a-zA-Z][a-zA-Z0-9.#+\-]{1,}/g) || [];
  return remaining;
}

const unregistered = new Map(); // token → 出現箇所リスト
for (const scene of map.scenes) {
  for (const line of scene.lines) {
    const tokens = detectUnregisteredTokens(line.text);
    for (const token of tokens) {
      if (!unregistered.has(token)) unregistered.set(token, []);
      unregistered.get(token).push(`scene ${scene.id}: "${line.text}"`);
    }
  }
}

if (unregistered.size > 0) {
  console.error(`\n❌ 未登録の英単語が ${unregistered.size} 件見つかりました。DICTに追加してください:\n`);
  for (const [token, locations] of unregistered) {
    console.error(`  ⚠️  "${token}"`);
    console.error(`      例: ${locations[0]}`);
  }
  console.error(`\nadd_readings.js の DICT に上記の単語とカタカナ読みを追加してください。`);
  console.error('読み間違いを防ぐため、未登録の英単語がある状態では処理を中断します。\n');
  process.exit(1);
}

// バックアップ保存
if (!fs.existsSync(BAK_FILE)) {
  fs.copyFileSync(MAP_FILE, BAK_FILE);
}

fs.writeFileSync(MAP_FILE, JSON.stringify(map, null, 2), 'utf-8');
console.log(`Done! ${modified} lines got "reading" field added.`);
